<?php
/** @var \Magento\Framework\View\Element\AbstractBlock $block */
/** @var \Piuga\News\ViewModel\CategoryView $viewModel */
$viewModel = $block->getViewModel();
$category = $viewModel->getNewsCategory();
?>
<div class="category-view">
    <div class="no-display"><?= $block->escapeHtml($category->getTitle()) ?></div>
    <?php if ($category->getContent()): ?>
        <div class="category-description">
            <?= $category->getContent(); ?>
        </div>
    <?php endif; ?>
</div>
