<?php
/** @var \Magento\Framework\View\Element\AbstractBlock $block */
/** @var \Piuga\News\ViewModel\NewsView $viewModel */
$viewModel = $block->getViewModel();
$news = $viewModel->getNewsItem();
?>
<div class="news-view" itemscope itemtype="http://schema.org/Article">
    <div class="no-display" itemprop="name"><?= $block->escapeHtml($news->getTitle()) ?></div>
    <?php if ($news->getImage()): ?>
        <div class="news-image">
            <span itemprop="image">
                <img
                    src="<?= $news->getImageUrl() ?>"
                    alt="<?= $block->escapeHtml($news->getTitle()) ?>"
                    title="<?= $block->escapeHtml($news->getTitle()) ?>"
                />
            </span>
        </div>
    <?php endif; ?>
    <div class="news-content" itemprop="articleBody">
        <?= $news->getContent() ?>
        <?php if ($news->getFile()): ?>
            <div class="more-info">
                <?= __('For more information <a href="%1" target="_blank">download this</a> file.', $news->getFileUrl()); ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="author-date">
        <span class="author">
            <?= __('by') ?>
            <span itemprop="author"><?= $block->escapeHtml($news->getAuthor()) ?></span>
        </span>
        <span class="date">
            <?= __('published at') ?>
            <span itemprop="datePublished"><?= $block->escapeHtml($viewModel->getPublishDate($news)) ?></span>
        </span>
    </div>
</div>
