<?php
/** @var \Piuga\News\Block\Adminhtml\Category\AssignNews $block */
/** @var \Piuga\News\Block\Adminhtml\Category\Tab\News $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input type="hidden" name="category_news" id="in_category_news" data-form-part="piuga_news_category_form" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Piuga_News/js/category/assign-news": {
                "selectedNews": <?= $block->getNewsJson(); ?>,
                "gridJsObjectName": <?= '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
